# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Рабочая группа по обеспечению качества работы СКЦ
#email: super-no-shit-please@parallel.ru
#description: >- # this means to ignore newlines until "baseurl:"
#  Рабочая группа по обеспечению качества работы СКЦ. Членство
#  в группе бесплатное, на добровольных началах.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://scc-efficiency.parallel.ru" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
theme: minima
header_pages:
  - index

plugins:
  - jekyll-feed
  - jekyll-spaceship
  - jekyll-gist

sass:
  sass_dir: _sass
  style: compact

deploy:
  - rsync -aze ssh --delete ./ graphit:scc-efficiency/_site/
  - ssh graphit sudo scc-efficiency/update.sh

jekyll-spaceship:
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - polyfill-processor
    - video-processor
    - emoji-processor
  mathjax-processor:
    src:  //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    config:
      tex2jax:
        inlineMath:
          - ['$','$']
          - ['\(','\)']
  plantuml-processor:
    src: http://www.plantuml.com/plantuml/png/
  emoji-processor:
    src: https://github.githubassets.com/images/icons/emoji/


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
